const mongoose = require("mongoose");

const volunteerSchema = new mongoose.Schema(
  {
    fullName: { type: String, required: true },
    email: { type: String, required: true, unique: true, lowercase: true, trim: true },
    phone: { type: String, required: true },
    address: { type: String, default: "" },
    gender: { type: String, default: "" },
    city: { type: String, default: "" },
    state: { type: String, default: "" },
    pincode: { type: String, default: "" },
    dateOfBirth: { type: String, default: "" },
    education: { type: String, default: "" },
    educationOther: { type: String, default: "" },
    institution: { type: String, default: "" },
    occupation: { type: String, default: "" },
    occupationOther: { type: String, default: "" },
    skills: { type: [String], default: [] },
    skillsOther: { type: String, default: "" },
    interests: { type: [String], default: [] },
    capacity: { type: [String], default: [] },
    capacityOther: { type: String, default: "" },
    availability: { type: mongoose.Schema.Types.Mixed, default: {} },
    hoursPerWeek: { type: String, default: "" },
    experience: { type: String, default: "" },
    motivation: { type: String, default: "" },
    previousVolunteer: { type: String, default: "" },
    emergencyContact: {
      name: { type: String, default: "" },
      phone: { type: String, default: "" },
      relationship: { type: String, default: "" },
    },
    hearAbout: { type: String, default: "" },
    hearAboutOther: { type: String, default: "" },
    selectedOpportunityId: { type: String, default: "" },
    selectedOpportunityTitle: { type: String, default: "" },
    corePurpose: { type: String, default: "" },
    newLaw: { type: String, default: "" },
    viewOnSociety: { type: String, default: "" },
    leadershipAction: { type: String, default: "" },
    dailyHabit: { type: String, default: "" },
    agreeConduct: { type: Boolean, default: false },
    agreeDeclaration: { type: Boolean, default: false },
    status: {
      type: String,
      enum: ["pending", "approved", "rejected"],
      default: "pending",
    },
    passwordHash: { type: String, required: true, select: false },
  },
  { timestamps: true }
);

module.exports = mongoose.models.Volunteer || mongoose.model("Volunteer", volunteerSchema);
